#!/usr/bin/env bash
set -e
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGE_NAME="gcm-tool"
ZSHRC="$HOME/.zshrc"

# Check Docker is installed
if ! command -v docker &>/dev/null; then
  echo "Error: Docker is not installed. Please install Docker first." >&2
  exit 1
fi

echo "Building Docker image '$IMAGE_NAME'..."
docker build -t "$IMAGE_NAME" "$SCRIPT_DIR"
echo "Docker image built successfully."

# Add to .zshrc if not already present
if grep -q "# gcm: AI-powered git commit" "$ZSHRC" 2>/dev/null; then
  echo "gcm function already exists in $ZSHRC — skipping."
else
  cat >> "$ZSHRC" << 'EOF'

# gcm: AI-powered git commit (auto-generated by gcm installer)
unalias gcm 2>/dev/null; true
function gcm() {
  local msg
  msg=$(docker run --rm -v "$(pwd):/workspace" -w /workspace \
    -e OPENAI_API_KEY="$OPENAI_API_KEY" gcm-tool 2>&1)
  local exit_code=$?
  if [ $exit_code -ne 0 ] || [ -z "$msg" ]; then
    echo "$msg" >&2
    return 1
  fi
  echo "Commit message: $msg"
  git commit -m "$msg"
}
# end gcm
EOF
  echo "gcm function added to $ZSHRC."
fi

# Warn if oh-my-zsh git plugin has a conflicting gcm alias
if grep -q "gcm=" "$HOME/.oh-my-zsh/plugins/git/git.plugin.zsh" 2>/dev/null; then
  echo ""
  echo "Warning: oh-my-zsh git plugin has a conflicting 'gcm' alias."
  echo "Add this line to ~/.zshrc (after oh-my-zsh is sourced) to override it:"
  echo "  unalias gcm 2>/dev/null; true"
fi

echo ""
echo "Installation complete!"
echo ""
echo "Next steps:"
echo "  1. Set your OpenAI API key:"
echo "       export OPENAI_API_KEY=sk-..."
echo "     (add this to ~/.zshrc to make it permanent)"
echo ""
echo "  2. Reload your shell:"
echo "       source ~/.zshrc"
echo ""
echo "  3. Use it:"
echo "       git add ."
echo "       gcm"
