#!/usr/bin/env bash
# set -e: 명령어가 실패하면 즉시 스크립트 종료
# set -o pipefail: 파이프 중간 명령어 실패도 감지
set -e
set -o pipefail

# 이 스크립트가 위치한 디렉토리 (Dockerfile, gitmsg.py가 있는 곳)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGE_NAME="gitmsg-tool"
ZSHRC="$HOME/.zshrc"

# Docker 설치 여부 확인
if ! command -v docker &>/dev/null; then
  echo "Error: Docker is not installed. Please install Docker first." >&2
  exit 1
fi

# Dockerfile을 기반으로 Docker 이미지 빌드
echo "Building Docker image '$IMAGE_NAME'..."
docker build -t "$IMAGE_NAME" "$SCRIPT_DIR"
echo "Docker image built successfully."

# 이미 설치된 경우 중복 추가 방지
if grep -q "# gitmsg: AI-powered git commit" "$ZSHRC" 2>/dev/null; then
  echo "gitmsg function already exists in $ZSHRC — skipping."
else
  # .zshrc에 gitmsg 함수 추가 (heredoc 방식, 변수 치환 없이 그대로 삽입)
  cat >> "$ZSHRC" << 'EOF'

# gitmsg: AI-powered git commit (auto-generated by gitmsg installer)
unalias gitmsg 2>/dev/null; true
function gitmsg() {
  local msg
  msg=$(docker run --rm -v "$(pwd):/workspace" -w /workspace \
    -e OPENAI_API_KEY="$OPENAI_API_KEY" gitmsg-tool 2>&1)
  local exit_code=$?
  if [ $exit_code -ne 0 ] || [ -z "$msg" ]; then
    echo "$msg" >&2
    return 1
  fi
  echo "Commit message: $msg"
  git commit -m "$msg"
}
# end gitmsg
EOF
  echo "gitmsg function added to $ZSHRC."
fi

# oh-my-zsh git 플러그인에 gitmsg alias가 있으면 충돌 경고
if grep -q "gitmsg=" "$HOME/.oh-my-zsh/plugins/git/git.plugin.zsh" 2>/dev/null; then
  echo ""
  echo "Warning: oh-my-zsh git plugin has a conflicting 'gitmsg' alias."
  echo "Add this line to ~/.zshrc (after oh-my-zsh is sourced) to override it:"
  echo "  unalias gitmsg 2>/dev/null; true"
fi

echo ""
echo "Installation complete!"
echo ""
echo "Next steps:"
echo "  1. Set your OpenAI API key:"
echo "       export OPENAI_API_KEY=sk-..."
echo "     (add this to ~/.zshrc to make it permanent)"
echo ""
echo "  2. Reload your shell:"
echo "       source ~/.zshrc"
echo ""
echo "  3. Use it:"
echo "       git add ."
echo "       gitmsg"
